//
//  LicensesView.swift
//  Pelagica
//

import SwiftUI

/// A bundled dependency license, generated by `scripts/generate_licenses.py`.
struct OpenSourceLicense: Decodable, Identifiable, Hashable {
    let name: String
    let version: String?
    let url: String
    let license: String
    let text: String

    var id: String { name }

    static let all: [OpenSourceLicense] = {
        guard let url = Bundle.main.url(forResource: "licenses", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let licenses = try? JSONDecoder().decode([OpenSourceLicense].self, from: data) else {
            return []
        }
        return licenses
    }()
}

struct LicensesView: View {
    var body: some View {
        ZStack {
            PelagicaBackground()

            ScrollView {
                VStack(alignment: .leading, spacing: 40) {
                    VStack(alignment: .leading, spacing: 12) {
                        Text(i18n.t("settings:open_source_licenses_title"))
                            .font(.system(size: 40, weight: .bold))
                            .foregroundStyle(.white)

                        Text(i18n.t("settings:pelagica_license_notice", ["license": "GPL-3.0", "url": "github.com/PelagicaApp/pelagica-atv"]))
                            .font(.system(size: 22))
                            .foregroundStyle(.secondary)
                    }

                    VStack(spacing: 16) {
                        ForEach(OpenSourceLicense.all) { license in
                            NavigationLink {
                                LicenseDetailView(license: license)
                            } label: {
                                LicenseRow(license: license)
                            }
                            .buttonStyle(PelagicaButtonStyle(emphasis: .secondary))
                        }
                    }
                }
                .padding(60)
                .frame(maxWidth: .infinity, alignment: .topLeading)
            }
        }
    }
}

private struct LicenseRow: View {
    let license: OpenSourceLicense

    var body: some View {
        HStack {
            Text(license.name)

            if let version = license.version {
                Text(version)
                    .foregroundStyle(.secondary)
            }

            Spacer()

            Text(license.license)
                .foregroundStyle(.secondary)
        }
    }
}

private struct LicenseDetailView: View {
    let license: OpenSourceLicense
    
    var body: some View {
        ZStack {
            PelagicaBackground()
            
            VStack(alignment: .leading, spacing: 32) {
                VStack(alignment: .leading, spacing: 8) {
                    Text(license.name)
                        .font(.system(size: 40, weight: .bold))
                        .foregroundStyle(.white)
                    
                    Text("\(license.license) ⋅ \(license.url)")
                        .font(.system(size: 22))
                        .foregroundStyle(.secondary)
                }
                
                LicenseTextView(text: license.text)
            }
            .padding(60)
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
        }
    }
}

private struct LicenseTextView: UIViewRepresentable {
    let text: String
    
    func makeUIView(context: Context) -> UITextView {
        let textView = UITextView()
        textView.backgroundColor = .clear
        textView.textColor = UIColor.white.withAlphaComponent(0.85)
        textView.font = .monospacedSystemFont(ofSize: 20, weight: .regular)
        textView.isSelectable = true
        textView.isScrollEnabled = true
        textView.isUserInteractionEnabled = true
        textView.panGestureRecognizer.allowedTouchTypes = [NSNumber(value: UITouch.TouchType.indirect.rawValue)]
        textView.showsVerticalScrollIndicator = true
        return textView
    }
    
    func updateUIView(_ textView: UITextView, context: Context) {
        if textView.text != text {
            textView.text = text
        }
    }
}

#Preview {
    NavigationStack {
        LicensesView()
    }
}
